url:
  url1: www.jackyroc.com

server:
  port: 8081
  servlet:
    session:
      timeout: 30m #30分钟
  tomcat:
    connection-timeout: 18000000

spring:
  application:
    name: JackyTest
  datasource:
    url: jdbc:mysql://jdbc:mysql://127.0.0.1:3306/testspring?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: jacky123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jackytest.demo.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.jackytest.demo.dao: debug  #打印sql
